export const FILE_INFO_REQUEST = 'FILE_INFO_REQUEST';
export const FILE_INFO_SUCCESS = 'FILE_INFO_SUCCESS';
export const FILE_INFO_FAIL = 'FILE_INFO_FAIL';
export const FILE_INFO_RESET = 'FILE_INFO_RESET';
